config/routes.rb
Etest::Application.routes.draw do
  devise_for :users, :admins
  resources :users
  resources :admins
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable,
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit! }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if current_admin 
      @users = User.all
    end
  end

  def help
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/index.html.erb
<h1>Admins#index</h1>
<%if admin_signed_in? %>
<p>Hello, admin <%= current_admin.email%> !</p>

<%end %>

app/views/layouts/_footer.html.erb
<div class="span3">
  <h2>About Us</h2>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>

<div class="span12">
  <p>All rights reserved  © Etest </p>
</div>

app/views/layouts/_header.html.erb
<div class="navbar">
<div class="navbar-inner">
<ul class="nav pull-right">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Help", help_path %></li>

  <% case %>
  <% when admin_signed_in?%>
    <li id="fat-menu" class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Settings", '#' %></li>
        <li class="divider"></li>
        <li>
          <%= link_to "Logout", destroy_admin_session_path, :method => :delete %>
        </li>
      </ul>
    </li>
    <li> <%= link_to "Logout", destroy_admin_session_path, :method => :delete %></li>

  <% when user_signed_in?%>
    <li id="fat-menu" class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Profile", edit_user_registration_path %></li>
        <li><%= link_to "Settings", '#' %></li>
        <li class="divider"></li>
        <li>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
        </li>
      </ul>
    </li>
    <li> <%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>

  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
  <% end %>

</ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Etest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

      <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
      <% end %>

  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
  <%= render 'layouts/footer' %>  
    </div>
  </div>
</body>

</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<br>
<% case %>
  <% when admin_signed_in?%>
  <p>Hello, admin <%= current_admin.email%> !</p>
  <ul><% @users.each do |user| %>
    <li> <%= user.email %> </li>
  </ul> <% end %>
  <% when user_signed_in?%>
  <p>Hello, user <%= current_user.email%> !</p>
  <% else %>
  <p>We are waiting for you <%= link_to "Sign up"%></p>
<% end %>